### ISSUE TITLE
"Kube" not showing in menu

### ISSUE THREAD

**Issue by grstein** [njust/KTail#1]
Hi, your project is really interesting, keep this up! I'm running it in an Arch Linux and the "kube" menu item isn't showing. 
My ~/.kube/ is populated with my clusters' yamls. What more should I have to ktail properly identify my clusters?

**Comment by njust** [comment]
Hi, thanks for your feedback. The menu item should be visible if you have a ~/.kube/config file in place. An alternative config file set via KUBECONFIG environment variable is currently not recognized.

**Comment by grstein** [comment]
Thanks for your rapid response! As I have more than one K8S cluster, there are multiples files in my .kube, none of them is named config. I rely in KUBECONFIG environment variable to use K9S, for example. It would be nice if I could put the .kube file as a parameter like `ktail -c dev.yaml`.

**Comment by njust** [comment]
I added the option to specify the path to the kubernetes config file with the following priority:
- Command parameter ./ktail -c /path/to/.kube/config
- KUBECONFIG environment variable
- Default location at ~/home/.kube/config 

You can find the new version here:
https://www.ktail.de/downloads/ktail-v031/

Please let me know if that works for you, so we can close this issue.

**Comment by grstein** [comment]
Perfect!
