### ISSUE TITLE
How to view timestamps?

### ISSUE THREAD

**Issue by tgeorge91** [njust/KTail#4]
Hello, I apologize for my ignorance, as my exposure to kubernetes is rather low, and my exposure to rust is non existent, but is there way to view timestamps? I chose this app since it goes back further than cmd in windows, but in cmd I'm able to add "--timestamps=true" to the command. Is there something similar in KTail that I'm missing?

Thank you!

**Comment by njust** [comment]
Hello, thank you for raising the issue. I had already planned to add an option to display timestamps. Initially I assumed that log data usually already contains some kind of timestamp, so I didn't already include it in the log view, even though it is already used internally.

**Comment by njust** [comment]
Timestamps can now be enabled via the menu in the toolbar:
![image](https://user-images.githubusercontent.com/2380253/152647862-e4f1d67a-aa79-4127-95d8-f833946a3d0a.png)
