### ISSUE TITLE
does this run on macOS catalina?

### ISSUE THREAD

**Issue by dennydharmawan** [njust/KTail#7]
I tried to open it open cataline but the UI doesn't seem to open

**Comment by njust** [comment]
Unfortunately not, since this change: https://github.com/njust/KTail/commit/56365630acac9ddc5ccb95e10145695e3823fc88 only macOS >= 11 is supported.

**Comment by njust** [comment]
You might want to check out https://kubelog.de/. I've tested it successfully on macOS Mojave and Ventura, so it should work on Catalina as well.

**Comment by dennydharmawan** [comment]
Thx for the info
